### ISSUE TITLE
Automate tracking latest Nickel

### ISSUE THREAD

**Issue by mboes** [tweag/nickel-lang.org#6]
**Is your feature request related to a problem? Please describe.**
We want Nickel documentation to be on the website, for both major releases and for current Nickel `master`. The Nickel documentation lives in the https://github.com/tweag/nickel repo. They happen asynchronously to updates in this repo. We can trigger a new deploy to production manually, but that's work. So we can automate this instead.

**Describe the solution you'd like**
1. Make the current production deploy workflow be triggered on a nightly schedule, not just by pull requests.
1. Replace the current submodule pointer to Nickel with flakes. Tell flakes to checkout the tip of each release branch and the tip of `master`. Build against whatever is the latest from each of these branches (see below regarding reproducibility).

**Describe alternatives you've considered**
An alternative is to record the tips of the release+master branches in the Git history at each deploy. However, if deploys happen on at least a nightly schedule, then the vast majority of the history in Git will be about that, because we don't update the website assets that often. I'd argue that the history of updates is not useful information. And we don't need the Git history to reproduce exactly a specific deploy.

cc @garbas. Original discussion: https://github.com/tweag/nickel-lang.org/pull/5#pullrequestreview-842664705.

Blocked on #7.

**Comment by garbas** [comment]
This was now fixed as `nickel` is now an handled by flake and being updated (via PRs weekly) using github workflow.
